// Infraestrutura estratégica nacional — instalações públicas e conhecidas
// (não são dados sigilosos; coordenadas e endereços verificados via fontes
// públicas: Wikipédia em português, sites oficiais .gov.br/.mil.br, e
// cruzamento com Google Maps quando necessário). Re-verificado em 2026-09
// via pesquisa dedicada — itens sem confirmação confiável de coordenada
// exata estão marcados com verified: false e o texto explica o porquê.
export type StrategicSiteKind =
  | "nuclear"
  | "hydro"
  | "aerospace"
  | "naval"
  | "airport"
  | "federal_police"
  | "border_post"
  | "power_grid"
  | "water_sanitation"
  | "army"
  | "port"
  | "telecom";

export interface StrategicSite {
  id: string;
  name: string;
  kind: StrategicSiteKind;
  state: string;
  latitude: number;
  longitude: number;
  address?: string;
  contact?: string;
  description: string;
  /** false = coordenada aproximada (endereço público confirmado, mas sem geocodificação exata cruzada) */
  verified: boolean;
}

export const STRATEGIC_SITES: StrategicSite[] = [
  // --- Nuclear ---
  {
    id: "inb-caetite",
    name: "INB Caetité — Unidade de Concentrado de Urânio",
    kind: "nuclear",
    state: "BA",
    latitude: -13.8339,
    longitude: -42.2936,
    address: "Fazenda Cachoeira, s/nº, Caixa Postal 7, CEP 46400-000, Caetité – BA",
    contact: "(77) 3454-4850 · inbcaetite@inb.gov.br",
    description: "Mineração e beneficiamento de urânio (Indústrias Nucleares do Brasil), ~40 km do centro de Caetité.",
    verified: true,
  },
  {
    id: "inb-resende",
    name: "INB Resende — Fábrica de Combustível Nuclear",
    kind: "nuclear",
    state: "RJ",
    latitude: -22.4707,
    longitude: -44.4703,
    address: "Rodovia Presidente Dutra, km 336, Eng. Passos, CEP 27555-000, Resende – RJ",
    contact: "(24) 3321-8844/8880/8944 · inbresende@inb.gov.br",
    description: "Enriquecimento e fabricação de combustível nuclear.",
    verified: false,
  },
  {
    id: "angra-nuclear",
    name: "Central Nuclear Almirante Álvaro Alberto (Angra 1/2/3)",
    kind: "nuclear",
    state: "RJ",
    latitude: -23.0083,
    longitude: -44.4739,
    address: "Rod. Gov. Mário Covas (BR-101 Sul), km 517/521,56, Praia de Itaorna, Angra dos Reis – RJ, CEP 23948-000",
    contact: "(24) 3362-9000 · presidencia@eletronuclear.gov.br",
    description: "Angra 1 e 2 em operação comercial; Angra 3 em construção (confirme status atualizado antes de tratar como planta completa).",
    verified: true,
  },
  // --- Naval/Defesa ---
  {
    id: "aramar",
    name: "CTMSP Aramar (Centro Experimental Aramar)",
    kind: "naval",
    state: "SP",
    latitude: -23.4189,
    longitude: -47.6122,
    address: "Estrada Sorocaba-Iperó, km 12,5, Iperó – SP, CEP 18560-000 (dentro da Fazenda Ipanema)",
    description: "Centro Tecnológico da Marinha — programa do submarino nuclear brasileiro. Coordenada aproximada (endereço confirmado, geocodificação exata do sítio de Iperó não cruzada).",
    verified: false,
  },
  {
    id: "base-naval-rio",
    name: "Base Naval do Rio de Janeiro",
    kind: "naval",
    state: "RJ",
    latitude: -22.8964,
    longitude: -43.1742,
    address: "Praça Barão de Ladário, s/nº, Ed. 17A, Ilha das Cobras, Centro, RJ, CEP 20091-000",
    contact: "(21) 2178-5722 · bnic.secom@marinha.mil.br",
    description: "Principal base da Marinha do Brasil.",
    verified: true,
  },
  {
    id: "base-naval-aratu",
    name: "Base Naval de Aratu",
    kind: "naval",
    state: "BA",
    latitude: -12.8128,
    longitude: -38.4886,
    address: "Estrada da Base Naval, s/nº, São Tomé de Paripe, Salvador – BA, CEP 40800-310",
    contact: "(71) 3307-3400",
    description: "Base naval e estaleiro da Marinha na Baía de Todos os Santos.",
    verified: true,
  },
  {
    id: "base-aerea-anapolis",
    name: "Base Aérea de Anápolis",
    kind: "naval",
    state: "GO",
    latitude: -16.2386,
    longitude: -48.9722,
    address: "BR-414, km 4, Zona Rural, Anápolis – GO, CEP 75024-970",
    description: "Principal base de caça da Força Aérea Brasileira.",
    verified: true,
  },
  // --- Hidrelétricas ---
  {
    id: "itaipu",
    name: "Usina Hidrelétrica de Itaipu",
    kind: "hydro",
    state: "PR",
    latitude: -25.4078,
    longitude: -54.59,
    address: "Av. Tancredo Neves, 6702, Foz do Iguaçu – PR, CEP 85856-970",
    description: "Uma das maiores hidrelétricas do mundo, fronteira Brasil-Paraguai.",
    verified: true,
  },
  {
    id: "tucurui",
    name: "Usina Hidrelétrica de Tucuruí",
    kind: "hydro",
    state: "PA",
    latitude: -3.8322,
    longitude: -49.6497,
    address: "Rodovia BR-422, km 13, Tucuruí – PA",
    description: "Maior hidrelétrica genuinamente brasileira.",
    verified: true,
  },
  {
    id: "belo-monte",
    name: "Usina Hidrelétrica de Belo Monte",
    kind: "hydro",
    state: "PA",
    latitude: -3.1278,
    longitude: -51.7758,
    address: "Municípios de Vitória do Xingu / Altamira / Brasil Novo — PA (complexo sem endereço único)",
    description: "Complexo hidrelétrico no rio Xingu.",
    verified: true,
  },
  {
    id: "sobradinho",
    name: "Usina Hidrelétrica de Sobradinho",
    kind: "hydro",
    state: "BA",
    latitude: -9.4303,
    longitude: -40.8272,
    address: "Municípios de Sobradinho e Casa Nova – BA",
    description: "Grande reservatório do rio São Francisco, abastece o semiárido nordestino.",
    verified: true,
  },
  // --- Aeroespacial ---
  {
    id: "alcantara",
    name: "Centro Espacial de Alcântara (CEA)",
    kind: "aerospace",
    state: "MA",
    latitude: -2.3333,
    longitude: -44.4,
    address: "Município de Alcântara – MA, ~32 km de São Luís",
    description: "Base de lançamento de foguetes e satélites (nome oficial atualizado — era \"Centro de Lançamento de Alcântara\").",
    verified: true,
  },
  {
    id: "clbi-barreira-do-inferno",
    name: "Centro de Lançamento da Barreira do Inferno",
    kind: "aerospace",
    state: "RN",
    latitude: -5.925,
    longitude: -35.1631,
    address: "Parnamirim – RN, próximo a Ponta Negra/Natal",
    description: "Primeiro centro de lançamento de foguetes do Brasil.",
    verified: true,
  },
  // --- Aeroportos (coordenadas ICAO, alta confiabilidade) ---
  {
    id: "aero-bsb",
    name: "Aeroporto Internacional de Brasília (BSB)",
    kind: "airport",
    state: "DF",
    latitude: -15.8711,
    longitude: -47.9186,
    address: "Área Especial s/n, Lago Sul, Brasília – DF, CEP 71608-900",
    description: "Principal hub da capital federal.",
    verified: true,
  },
  {
    id: "aero-gru",
    name: "Aeroporto Internacional de Guarulhos (GRU)",
    kind: "airport",
    state: "SP",
    latitude: -23.4356,
    longitude: -46.4731,
    address: "Rod. Hélio Smidt, s/n, Cumbica, Guarulhos – SP, CEP 07190-100",
    description: "Maior aeroporto do Brasil em movimento de passageiros e cargas.",
    verified: true,
  },
  {
    id: "aero-cgh",
    name: "Aeroporto de Congonhas (CGH)",
    kind: "airport",
    state: "SP",
    latitude: -23.6261,
    longitude: -46.6564,
    description: "Principal ponte aérea doméstica, zona urbana de São Paulo.",
    verified: true,
  },
  {
    id: "aero-gig",
    name: "Aeroporto Internacional do Galeão (GIG)",
    kind: "airport",
    state: "RJ",
    latitude: -22.81,
    longitude: -43.2506,
    address: "Av. 20 de Janeiro, s/nº, Ilha do Governador, RJ",
    description: "Principal aeroporto internacional do Rio de Janeiro.",
    verified: true,
  },
  {
    id: "aero-cnf",
    name: "Aeroporto Internacional de Confins / Belo Horizonte (CNF)",
    kind: "airport",
    state: "MG",
    latitude: -19.6239,
    longitude: -43.9714,
    address: "Confins – MG",
    description: "Principal aeroporto internacional de Minas Gerais.",
    verified: true,
  },
  {
    id: "aero-ssa",
    name: "Aeroporto Internacional de Salvador (SSA)",
    kind: "airport",
    state: "BA",
    latitude: -12.9086,
    longitude: -38.3225,
    address: "Praça Gago Coutinho, s/n, São Cristóvão, Salvador – BA",
    description: "Principal hub aéreo do Nordeste soteropolitano.",
    verified: true,
  },
  {
    id: "aero-rec",
    name: "Aeroporto Internacional do Recife (REC)",
    kind: "airport",
    state: "PE",
    latitude: -8.1264,
    longitude: -34.9228,
    address: "Praça Min. Salgado Filho, s/n, Imbiribeira, Recife – PE",
    description: "Principal hub aéreo do Nordeste.",
    verified: true,
  },
  {
    id: "aero-for",
    name: "Aeroporto Internacional de Fortaleza (FOR)",
    kind: "airport",
    state: "CE",
    latitude: -3.7758,
    longitude: -38.5322,
    address: "Av. Sen. Carlos Jereissati, 3000, Serrinha, Fortaleza – CE",
    description: "Principal porta de entrada aérea do Ceará.",
    verified: true,
  },
  {
    id: "aero-bel",
    name: "Aeroporto Internacional de Belém (BEL)",
    kind: "airport",
    state: "PA",
    latitude: -1.3844,
    longitude: -48.4789,
    address: "Av. Júlio César, s/n, Val-de-Cans, Belém – PA",
    description: "Principal porta de entrada aérea da Amazônia oriental.",
    verified: true,
  },
  {
    id: "aero-mao",
    name: "Aeroporto Internacional de Manaus (MAO)",
    kind: "airport",
    state: "AM",
    latitude: -3.0411,
    longitude: -60.0506,
    address: "Av. Santos Dumont, 1350, Tarumã, Manaus – AM",
    description: "Principal hub aéreo da Amazônia ocidental, zona franca.",
    verified: true,
  },
  {
    id: "aero-poa",
    name: "Aeroporto Internacional de Porto Alegre (POA)",
    kind: "airport",
    state: "RS",
    latitude: -29.9947,
    longitude: -51.1711,
    address: "Av. Severo Dullius, 90010, Anchieta, Porto Alegre – RS",
    description: "Principal hub aéreo do extremo sul do Brasil.",
    verified: true,
  },
  {
    id: "aero-cwb",
    name: "Aeroporto Internacional de Curitiba/Afonso Pena (CWB)",
    kind: "airport",
    state: "PR",
    latitude: -25.5317,
    longitude: -49.1761,
    address: "Av. Rocha Pombo, s/n, São José dos Pinhais – PR (região metropolitana de Curitiba, não na capital)",
    description: "Principal hub aéreo do sul do Brasil.",
    verified: true,
  },
  {
    id: "aero-igu",
    name: "Aeroporto Internacional de Foz do Iguaçu (IGU)",
    kind: "airport",
    state: "PR",
    latitude: -25.6003,
    longitude: -54.485,
    description: "Tríplice fronteira Brasil-Argentina-Paraguai.",
    verified: true,
  },
  {
    id: "aero-vdc",
    name: "Aeroporto de Vitória da Conquista (VDC)",
    kind: "airport",
    state: "BA",
    latitude: -14.9078,
    longitude: -40.9147,
    description: "Principal aeroporto do interior sudoeste da Bahia (coordenada ICAO SBVC).",
    verified: true,
  },
  {
    id: "aero-bvb",
    name: "Aeroporto Internacional de Boa Vista (BVB)",
    kind: "airport",
    state: "RR",
    latitude: 2.8414,
    longitude: -60.6922,
    description: "Porta de entrada aérea da fronteira norte, próxima à Venezuela.",
    verified: true,
  },
  {
    id: "aero-vix",
    name: "Aeroporto de Vitória (VIX)",
    kind: "airport",
    state: "ES",
    latitude: -20.2581,
    longitude: -40.2864,
    address: "Av. Roza Helena Schorling Albuquerque, s/n, Vitória – ES",
    description: "Principal aeroporto do Espírito Santo.",
    verified: true,
  },
  // --- Delegacias/Superintendências da Polícia Federal (sedes) ---
  {
    id: "pf-sr-sp",
    name: "Superintendência da PF em São Paulo",
    kind: "federal_police",
    state: "SP",
    latitude: -23.5285,
    longitude: -46.6949,
    address: "Rua Hugo D'Antola, 95, Lapa de Baixo, SP, CEP 05038-090",
    description: "Sede da Polícia Federal no estado de São Paulo.",
    verified: true,
  },
  {
    id: "pf-sr-rj",
    name: "Superintendência da PF no Rio de Janeiro",
    kind: "federal_police",
    state: "RJ",
    latitude: -22.897,
    longitude: -43.1917,
    address: "Av. Rodrigues Alves, 1, Saúde/Praça Mauá, RJ, CEP 20081-250",
    description: "Sede da Polícia Federal no estado do Rio de Janeiro.",
    verified: true,
  },
  {
    id: "pf-sr-df",
    name: "Superintendência da PF no Distrito Federal",
    kind: "federal_police",
    state: "DF",
    latitude: -15.8064,
    longitude: -47.8952,
    address: "SAIS Quadra 7, Lote 23, Setor Policial Sul, Brasília, CEP 70610-902",
    description: "Sede da Polícia Federal na capital federal.",
    verified: true,
  },
  {
    id: "pf-sr-ba",
    name: "Superintendência da PF na Bahia",
    kind: "federal_police",
    state: "BA",
    latitude: -12.9364,
    longitude: -38.4939,
    address: "Av. Eng. Oscar Pontes, 339, Água de Meninos, Salvador, CEP 40015-600",
    description: "Sede da Polícia Federal no estado da Bahia.",
    verified: true,
  },
  {
    id: "pf-sr-pe",
    name: "Superintendência da PF em Pernambuco",
    kind: "federal_police",
    state: "PE",
    latitude: -8.0836,
    longitude: -34.8925,
    address: "Av. Antônio de Góes, 60, 15º andar, Pina, Recife (Edf. JCPM), CEP 51010-000",
    description: "Sede da Polícia Federal no estado de Pernambuco.",
    verified: true,
  },
  {
    id: "pf-sr-am",
    name: "Superintendência da PF no Amazonas",
    kind: "federal_police",
    state: "AM",
    latitude: -3.0897,
    longitude: -60.0217,
    address: "Av. Domingos Jorge Velho, 40, D. Pedro II, Manaus, CEP 69042-470",
    description: "Sede da Polícia Federal no estado do Amazonas.",
    verified: true,
  },
  {
    id: "pf-sr-rs",
    name: "Superintendência da PF no Rio Grande do Sul",
    kind: "federal_police",
    state: "RS",
    latitude: -30.0447,
    longitude: -51.2119,
    address: "Av. Ipiranga, 1365, Azenha, Porto Alegre, CEP 90160-093",
    description: "Sede da Polícia Federal no estado do Rio Grande do Sul.",
    verified: true,
  },
  {
    id: "pf-sr-pr",
    name: "Superintendência da PF no Paraná",
    kind: "federal_police",
    state: "PR",
    latitude: -25.3872,
    longitude: -49.2494,
    address: "Rua Prof.ª Sandália Monzón, 210, Santa Cândida, Curitiba, CEP 82640-040",
    description: "Sede da Polícia Federal no estado do Paraná.",
    verified: true,
  },
  {
    id: "pf-sr-mg",
    name: "Superintendência da PF em Minas Gerais",
    kind: "federal_police",
    state: "MG",
    latitude: -19.9331,
    longitude: -43.9581,
    address: "Rua Nascimento Gurgel, 30, Gutierrez, Belo Horizonte, CEP 30430-340",
    description: "Sede da Polícia Federal no estado de Minas Gerais.",
    verified: true,
  },
  {
    id: "pf-sr-ce",
    name: "Superintendência da PF no Ceará",
    kind: "federal_police",
    state: "CE",
    latitude: -3.7469,
    longitude: -38.5183,
    address: "Av. Borges de Melo, 820, Bairro de Fátima, Fortaleza, CEP 60415-510",
    description: "Sede da Polícia Federal no estado do Ceará.",
    verified: true,
  },
  // --- Postos de fronteira (controle migratório) ---
  {
    id: "pf-foz-iguacu",
    name: "Delegacia da PF — Foz do Iguaçu (fronteira tríplice)",
    kind: "border_post",
    state: "PR",
    latitude: -25.5478,
    longitude: -54.5882,
    description: "Controle migratório na fronteira Brasil-Argentina-Paraguai, Ponte da Amizade. Endereço exato do posto não confirmado nesta rodada — coordenada aproximada da região da ponte.",
    verified: false,
  },
  {
    id: "pf-uruguaiana",
    name: "Delegacia da PF — Uruguaiana (fronteira com Argentina)",
    kind: "border_post",
    state: "RS",
    latitude: -29.7546,
    longitude: -57.0864,
    address: "Rua dos Andradas, 1870, Santo Antônio, Uruguaiana – RS, CEP 97502-114 (endereço com confiança moderada, recomenda-se conferência local)",
    description: "Controle migratório e aduaneiro, Ponte Internacional da Concórdia.",
    verified: false,
  },
  {
    id: "pf-corumba",
    name: "Delegacia da PF — Corumbá (fronteira com Bolívia)",
    kind: "border_post",
    state: "MS",
    latitude: -19.0078,
    longitude: -57.6547,
    address: "Praça da República, 51, Centro, Corumbá – MS, CEP 79301-140",
    description: "Controle migratório na fronteira com a Bolívia.",
    verified: true,
  },
  {
    id: "pf-tabatinga",
    name: "Delegacia da PF — Tabatinga (fronteira com Colômbia/Peru)",
    kind: "border_post",
    state: "AM",
    latitude: -4.2517,
    longitude: -69.9386,
    address: "Av. da Amizade, 26, Ibirapuera, Tabatinga – AM, CEP 69640-000",
    description: "Tríplice fronteira amazônica, Brasil-Colômbia-Peru.",
    verified: true,
  },
  {
    id: "pf-pacaraima",
    name: "Delegacia da PF — Pacaraima (fronteira com Venezuela)",
    kind: "border_post",
    state: "RR",
    latitude: 4.4394,
    longitude: -61.1514,
    address: "Av. Brasil, s/n, BR-174, Pacaraima – RR, CEP 69345-000",
    description: "Principal ponto de entrada terrestre da fronteira com a Venezuela.",
    verified: true,
  },
  {
    id: "pf-santana-do-livramento",
    name: "Delegacia da PF — Santana do Livramento (fronteira com Uruguai)",
    kind: "border_post",
    state: "RS",
    latitude: -30.8908,
    longitude: -55.5328,
    address: "Rua Silveira Martins, 1257, Centro, CEP 97573-511",
    description: "Cidades-gêmeas Livramento/Rivera, fronteira seca com o Uruguai.",
    verified: true,
  },
  // --- Energia (subestações e refinarias) ---
  {
    id: "se-ibiuna",
    name: "Subestação Ibiúna",
    kind: "power_grid",
    state: "SP",
    latitude: -23.6649,
    longitude: -47.1032,
    address: "Rod. Bunjiro Nakao (SP-250), Ibiúna – SP, CEP 18150-000",
    description: "Principal ponto de conversão da energia de Itaipu (corrente contínua) pro sistema interligado nacional — operada por Furnas.",
    verified: true,
  },
  {
    id: "se-foz-furnas",
    name: "Subestação Foz do Iguaçu (Furnas)",
    kind: "power_grid",
    state: "PR",
    latitude: -25.4102,
    longitude: -54.6122,
    address: "Av. Tarquínio Joslin dos Santos, 3555, Foz do Iguaçu – PR, CEP 85870-650",
    description: "Ponto de escoamento da energia gerada em Itaipu pro sistema brasileiro. A \"Margem Direita\" (lado 50Hz/paraguaio) é instalação distinta, não incluída aqui.",
    verified: true,
  },
  {
    id: "se-xingu",
    name: "Subestação Xingu — Belo Monte",
    kind: "power_grid",
    state: "PA",
    latitude: -3.21,
    longitude: -51.8,
    address: "Município de Anapu – PA, ~17 km da UHE Belo Monte",
    description: "Hub de conversão e transmissão da energia de Belo Monte. Coordenada aproximada — geocodificação exata não confirmada.",
    verified: false,
  },
  {
    id: "se-serra-da-mesa",
    name: "Subestação Serra da Mesa",
    kind: "power_grid",
    state: "GO",
    latitude: -13.8289,
    longitude: -48.3058,
    address: "GO-241, km 128/129, Zona Rural, Minaçu – GO, CEP 76450-000",
    description: "Nó estratégico de transmissão entre Norte/Nordeste e Sudeste do SIN.",
    verified: true,
  },
  {
    id: "replan",
    name: "REPLAN — Refinaria de Paulínia",
    kind: "power_grid",
    state: "SP",
    latitude: -22.7283,
    longitude: -47.1317,
    address: "Rodovia SP-332, km 130, Bonfim, Paulínia – SP, CEP 13147-900",
    description: "Maior refinaria de petróleo do Brasil (Petrobras).",
    verified: true,
  },
  {
    id: "reduc",
    name: "REDUC — Refinaria Duque de Caxias",
    kind: "power_grid",
    state: "RJ",
    latitude: -22.7181,
    longitude: -43.2706,
    address: "Rodovia Washington Luiz, km 113,7, Campos Elíseos, Duque de Caxias – RJ",
    description: "Grande refinaria da Petrobras na Baixada Fluminense.",
    verified: true,
  },
  {
    id: "refinaria-mataripe",
    name: "Refinaria de Mataripe (ex-RLAM)",
    kind: "power_grid",
    state: "BA",
    latitude: -12.7053,
    longitude: -38.5667,
    address: "Rodovia BA-523, km 4, São Francisco do Conde – BA, CEP 43900-000",
    description: "Principal refinaria do Nordeste. Vendida pela Petrobras em 2021 — hoje operada pela Acelen (Mubadala), não é mais estatal.",
    verified: true,
  },
  // --- Água e esgoto (saneamento crítico) ---
  {
    id: "eta-guaraú",
    name: "ETA Guaraú — Sistema Cantareira",
    kind: "water_sanitation",
    state: "SP",
    latitude: -23.4456,
    longitude: -46.6497,
    address: "Estrada Santa Inês, Cachoeirinha, São Paulo – SP (numeração exata varia entre fontes)",
    description: "Maior estação de tratamento de água da América Latina, abastece boa parte da Grande São Paulo (Sabesp).",
    verified: true,
  },
  {
    id: "eta-guandu",
    name: "ETA Guandu",
    kind: "water_sanitation",
    state: "RJ",
    latitude: -22.8069,
    longitude: -43.5967,
    address: "km 19,5 da BR-465 (antiga Rio–São Paulo), Nova Iguaçu – RJ",
    description: "Maior estação de tratamento de água do mundo em volume, abastece a Região Metropolitana do Rio. Coordenada aproximada do endereço.",
    verified: false,
  },
  {
    id: "ete-barueri",
    name: "ETE Barueri",
    kind: "water_sanitation",
    state: "SP",
    latitude: -23.4886,
    longitude: -46.8994,
    address: "Bairro Aldeia, Barueri – SP",
    description: "Maior estação de tratamento de esgoto da América Latina (Sabesp). Coordenada aproximada do bairro.",
    verified: false,
  },
  {
    id: "eta-theodoro-sampaio",
    name: "ETA Theodoro Sampaio (\"Bolandeira\")",
    kind: "water_sanitation",
    state: "BA",
    latitude: -12.9733,
    longitude: -38.4256,
    address: "Parque da Bolandeira, Av. Dom Eugênio Sales, Boca do Rio, Salvador – BA",
    description: "Principal estação de tratamento de água de Salvador (Embasa) — nome técnico oficial é \"Theodoro Sampaio\"; \"Bolandeira\" é o nome popular do local.",
    verified: true,
  },
  // --- Comandos do Exército ---
  {
    id: "cmp-brasilia",
    name: "Comando Militar do Planalto — QG do Exército",
    kind: "army",
    state: "DF",
    latitude: -15.79,
    longitude: -47.885,
    address: "Av. do Exército, s/n, Setor Militar Urbano, Brasília – DF, CEP 70630-901/903",
    description: "Sede do Comando do Exército Brasileiro.",
    verified: true,
  },
  {
    id: "cml-rio",
    name: "Comando Militar do Leste",
    kind: "army",
    state: "RJ",
    latitude: -22.9058,
    longitude: -43.1747,
    address: "Praça Duque de Caxias, 25, 8º andar, Centro, RJ, CEP 20221-260 (Palácio Duque de Caxias)",
    description: "Um dos maiores comandos do Exército, região Sudeste/RJ-ES.",
    verified: true,
  },
  {
    id: "cmse-sao-paulo",
    name: "Comando Militar do Sudeste",
    kind: "army",
    state: "SP",
    latitude: -23.5947,
    longitude: -46.6572,
    address: "Av. Sgt. Mário Kozel Filho, 222, Ibirapuera, SP, CEP 04005-903",
    description: "Comando do Exército responsável por São Paulo e Mato Grosso do Sul.",
    verified: true,
  },
  {
    id: "cma-manaus",
    name: "Comando Militar da Amazônia",
    kind: "army",
    state: "AM",
    latitude: -3.0669,
    longitude: -60.0217,
    address: "Av. Cel. Jorge Teixeira, 4715, Ponta Negra, Manaus, CEP 69037-000",
    description: "Comando responsável pela vigilância e defesa da fronteira amazônica.",
    verified: true,
  },
  {
    id: "cms-porto-alegre",
    name: "Comando Militar do Sul",
    kind: "army",
    state: "RS",
    latitude: -30.03,
    longitude: -51.2144,
    address: "Rua dos Andradas, 562, Centro, Porto Alegre, CEP 90029-900",
    description: "Comando do Exército responsável pela fronteira sul (Argentina/Uruguai).",
    verified: true,
  },
  {
    id: "cmne-recife",
    name: "Comando Militar do Nordeste",
    kind: "army",
    state: "PE",
    latitude: -8.0658,
    longitude: -34.9578,
    address: "BR-232, km 12, Curado, Recife, CEP 50950-000",
    description: "Comando do Exército responsável pela região Nordeste.",
    verified: true,
  },
  {
    id: "cmo-campo-grande",
    name: "Comando Militar do Oeste",
    kind: "army",
    state: "MS",
    latitude: -20.4547,
    longitude: -54.6019,
    address: "Av. Duque de Caxias, 1628, Amambai, Campo Grande, CEP 79100-900",
    description: "Comando do Exército responsável pela fronteira oeste (Bolívia/Paraguai).",
    verified: true,
  },
  // --- Portos estratégicos ---
  {
    id: "porto-santos",
    name: "Porto de Santos",
    kind: "port",
    state: "SP",
    latitude: -23.9822,
    longitude: -46.2925,
    address: "Av. Cons. Rodrigues Alves, s/n, Macuco, Santos – SP, CEP 11015-900",
    description: "Maior porto da América Latina em movimentação de cargas.",
    verified: true,
  },
  {
    id: "porto-paranagua",
    name: "Porto de Paranaguá",
    kind: "port",
    state: "PR",
    latitude: -25.5047,
    longitude: -48.5108,
    address: "Av. Ayrton Senna da Silva, 161, D. Pedro II, Paranaguá – PR, CEP 83203-800",
    description: "Segundo maior porto do país, principal escoadouro de grãos do Sul.",
    verified: true,
  },
  {
    id: "porto-itaqui",
    name: "Porto de Itaqui",
    kind: "port",
    state: "MA",
    latitude: -2.5725,
    longitude: -44.3642,
    address: "Av. dos Portugueses, s/n, São Luís – MA, CEP 65085-370",
    description: "Principal porto de águas profundas do Norte/Nordeste.",
    verified: true,
  },
  {
    id: "porto-suape",
    name: "Porto de Suape",
    kind: "port",
    state: "PE",
    latitude: -8.3958,
    longitude: -34.9678,
    address: "Rod. Indonésia, s/n, Distrito Industrial de Suape, Ipojuca – PE, CEP 55598-000",
    description: "Complexo industrial-portuário estratégico de Pernambuco.",
    verified: true,
  },
  {
    id: "porto-rio",
    name: "Porto do Rio de Janeiro",
    kind: "port",
    state: "RJ",
    latitude: -22.8919,
    longitude: -43.1953,
    address: "Av. Rodrigues Alves, 20, Centro, RJ, CEP 20081-000",
    description: "Principal porto da Baía de Guanabara.",
    verified: true,
  },
  // --- Telecomunicações / infraestrutura de internet ---
  {
    id: "ptt-sp",
    name: "PTT.br / IX.br São Paulo (NIC.br)",
    kind: "telecom",
    state: "SP",
    latitude: -23.5931,
    longitude: -46.6853,
    address: "Sede administrativa NIC.br: Av. das Nações Unidas, 11541, 7º andar, SP, CEP 04578-000",
    description: "Ponto de troca de tráfego de internet mais importante do país — NÃO é uma instalação física única: distribuído por múltiplos data centers comerciais (Equinix, TIVIT, Eletronet etc.) na região metropolitana de SP. Marcador representa a sede administrativa do NIC.br, não um ponto de peering exato.",
    verified: false,
  },
  {
    id: "ptt-rj",
    name: "PTT.br / IX.br Rio de Janeiro",
    kind: "telecom",
    state: "RJ",
    latitude: -22.9068,
    longitude: -43.1729,
    description: "Ponto de troca de tráfego de internet do Rio (IX.br) — assim como em SP, distribuído por múltiplos data centers, sem endereço físico único.",
    verified: false,
  },
  {
    id: "ptt-df",
    name: "PTT.br / IX.br Brasília",
    kind: "telecom",
    state: "DF",
    latitude: -15.7801,
    longitude: -47.9292,
    description: "Ponto de troca de tráfego de internet da capital federal (IX.br) — distribuído por múltiplos data centers, sem endereço físico único.",
    verified: false,
  },
];

export const STRATEGIC_KIND_META: Record<StrategicSiteKind, { label: string; icon: string; color: string }> = {
  nuclear: { label: "Nuclear", icon: "radio-outline", color: "#C05621" },
  hydro: { label: "Hidrelétrica", icon: "water-outline", color: "#1351B4" },
  aerospace: { label: "Aeroespacial", icon: "rocket-outline", color: "#5B21B6" },
  naval: { label: "Naval/Defesa", icon: "boat-outline", color: "#168821" },
  airport: { label: "Aeroporto", icon: "airplane-outline", color: "#0369A1" },
  federal_police: { label: "Polícia Federal", icon: "shield-outline", color: "#1E293B" },
  border_post: { label: "Posto de fronteira", icon: "flag-outline", color: "#B45309" },
  power_grid: { label: "Energia (rede/refinaria)", icon: "flash-outline", color: "#B7791F" },
  water_sanitation: { label: "Água/esgoto", icon: "water-outline", color: "#0E7490" },
  army: { label: "Exército", icon: "shield-half-outline", color: "#365314" },
  port: { label: "Porto", icon: "boat-outline", color: "#155E75" },
  telecom: { label: "Telecom/Internet", icon: "wifi-outline", color: "#6D28D9" },
};

// Rodovias federais principais, como polilinhas aproximadas (poucos pontos
// de referência — não é georreferenciamento preciso do traçado completo,
// mas o suficiente pra situar corredores logísticos/estratégicos no mapa).
export interface StrategicRoute {
  id: string;
  name: string;
  description: string;
  points: Array<{ latitude: number; longitude: number }>;
}

export const STRATEGIC_ROUTES: StrategicRoute[] = [
  {
    id: "br-101",
    name: "BR-101 (Rodovia Translitorânea)",
    description: "Principal eixo rodoviário do litoral, Natal (RN) a Osório (RS).",
    points: [
      { latitude: -5.79, longitude: -35.21 },
      { latitude: -8.05, longitude: -34.9 },
      { latitude: -12.97, longitude: -38.5 },
      { latitude: -19.92, longitude: -40.34 },
      { latitude: -22.9, longitude: -43.2 },
      { latitude: -26.3, longitude: -48.85 },
      { latitude: -29.94, longitude: -50.27 },
    ],
  },
  {
    id: "br-116",
    name: "BR-116 (Rodovia Régis Bittencourt/Fernão Dias)",
    description: "Principal corredor sul-nordeste, Fortaleza (CE) a Jaguarão (RS) — passa pelo interior da Bahia via Vitória da Conquista.",
    points: [
      { latitude: -3.78, longitude: -38.53 },
      { latitude: -8.05, longitude: -37.05 },
      { latitude: -12.97, longitude: -38.5 },
      { latitude: -14.87, longitude: -40.84 },
      { latitude: -17.24, longitude: -42.53 },
      { latitude: -19.92, longitude: -43.94 },
      { latitude: -23.55, longitude: -46.63 },
      { latitude: -26.3, longitude: -48.85 },
      { latitude: -30.03, longitude: -51.23 },
      { latitude: -32.57, longitude: -53.38 },
    ],
  },
  {
    id: "br-040",
    name: "BR-040",
    description: "Corredor Brasília (DF) – Rio de Janeiro (RJ), via Belo Horizonte.",
    points: [
      { latitude: -15.87, longitude: -47.92 },
      { latitude: -18.0, longitude: -46.0 },
      { latitude: -19.92, longitude: -43.94 },
      { latitude: -22.0, longitude: -43.4 },
      { latitude: -22.9, longitude: -43.2 },
    ],
  },
  {
    id: "br-364",
    name: "BR-364",
    description: "Corredor Cuiabá (MT) – Rio Branco (AC), integração centro-oeste/norte.",
    points: [
      { latitude: -15.6, longitude: -56.1 },
      { latitude: -12.6, longitude: -60.1 },
      { latitude: -9.97, longitude: -62.0 },
      { latitude: -8.76, longitude: -63.9 },
      { latitude: -9.97, longitude: -67.81 },
    ],
  },
  {
    id: "br-163",
    name: "BR-163",
    description: "Corredor logístico do agronegócio, Cuiabá (MT) a Santarém (PA).",
    points: [
      { latitude: -15.6, longitude: -56.1 },
      { latitude: -11.86, longitude: -55.5 },
      { latitude: -9.07, longitude: -55.1 },
      { latitude: -4.24, longitude: -55.99 },
      { latitude: -2.44, longitude: -54.71 },
    ],
  },
  {
    id: "br-230",
    name: "BR-230 (Transamazônica)",
    description: "Corredor leste-oeste da Amazônia, João Pessoa (PB) a Lábrea (AM).",
    points: [
      { latitude: -7.12, longitude: -34.86 },
      { latitude: -5.53, longitude: -47.48 },
      { latitude: -3.71, longitude: -49.68 },
      { latitude: -4.25, longitude: -55.99 },
      { latitude: -7.32, longitude: -64.8 },
      { latitude: -7.26, longitude: -64.8 },
    ],
  },
];
