// Infraestrutura estratégica nacional — instalações públicas e conhecidas
// (não são dados sigilosos; coordenadas aproximadas de domínio público,
// equivalentes às exibidas em mapas públicos como Google Maps/Wikipedia).
export type StrategicSiteKind =
  | "nuclear"
  | "hydro"
  | "aerospace"
  | "naval"
  | "airport"
  | "federal_police"
  | "border_post"
  | "power_grid"
  | "water_sanitation"
  | "army"
  | "port"
  | "telecom";

export interface StrategicSite {
  id: string;
  name: string;
  kind: StrategicSiteKind;
  state: string;
  latitude: number;
  longitude: number;
  description: string;
}

export const STRATEGIC_SITES: StrategicSite[] = [
  // --- Nuclear ---
  {
    id: "inb-caetite",
    name: "INB Caetité — Unidade de Concentrado de Urânio",
    kind: "nuclear",
    state: "BA",
    latitude: -14.0658,
    longitude: -42.4914,
    description: "Mineração e beneficiamento de urânio (Indústrias Nucleares do Brasil), Lagoa Real.",
  },
  {
    id: "inb-resende",
    name: "INB Resende — Fábrica de Combustível Nuclear",
    kind: "nuclear",
    state: "RJ",
    latitude: -22.4707,
    longitude: -44.4703,
    description: "Enriquecimento e fabricação de combustível nuclear.",
  },
  {
    id: "angra-nuclear",
    name: "Central Nuclear Almirante Álvaro Alberto (Angra 1/2/3)",
    kind: "nuclear",
    state: "RJ",
    latitude: -23.0064,
    longitude: -44.4547,
    description: "Usinas nucleares de Angra dos Reis, Praia de Itaorna.",
  },
  // --- Naval/Defesa ---
  {
    id: "aramar",
    name: "CTMSP Aramar",
    kind: "naval",
    state: "SP",
    latitude: -23.4189,
    longitude: -47.6122,
    description: "Centro Tecnológico da Marinha — programa do submarino nuclear brasileiro.",
  },
  {
    id: "base-naval-rio",
    name: "Base Naval do Rio de Janeiro",
    kind: "naval",
    state: "RJ",
    latitude: -22.8967,
    longitude: -43.1631,
    description: "Principal base da Marinha do Brasil, Ilha das Cobras.",
  },
  {
    id: "arsenal-marinha-ilha-mocangue",
    name: "Base Naval de Aratu",
    kind: "naval",
    state: "BA",
    latitude: -12.7889,
    longitude: -38.4931,
    description: "Base naval e estaleiro da Marinha na Baía de Todos os Santos.",
  },
  {
    id: "base-aerea-anapolis",
    name: "Base Aérea de Anápolis",
    kind: "naval",
    state: "GO",
    latitude: -16.2294,
    longitude: -48.9628,
    description: "Principal base de caça da Força Aérea Brasileira (esquadrões de F-5/Gripen).",
  },
  // --- Hidrelétricas ---
  {
    id: "itaipu",
    name: "Usina Hidrelétrica de Itaipu",
    kind: "hydro",
    state: "PR",
    latitude: -25.4082,
    longitude: -54.5892,
    description: "Uma das maiores hidrelétricas do mundo, fronteira Brasil-Paraguai.",
  },
  {
    id: "tucurui",
    name: "Usina Hidrelétrica de Tucuruí",
    kind: "hydro",
    state: "PA",
    latitude: -3.8283,
    longitude: -49.6442,
    description: "Maior hidrelétrica genuinamente brasileira.",
  },
  {
    id: "belo-monte",
    name: "Usina Hidrelétrica de Belo Monte",
    kind: "hydro",
    state: "PA",
    latitude: -3.0997,
    longitude: -51.7864,
    description: "Complexo hidrelétrico no rio Xingu.",
  },
  {
    id: "sobradinho",
    name: "Usina Hidrelétrica de Sobradinho",
    kind: "hydro",
    state: "BA",
    latitude: -9.4322,
    longitude: -40.8267,
    description: "Grande reservatório do rio São Francisco, abastece o semiárido nordestino.",
  },
  // --- Aeroespacial ---
  {
    id: "alcantara",
    name: "Centro de Lançamento de Alcântara",
    kind: "aerospace",
    state: "MA",
    latitude: -2.3736,
    longitude: -44.3959,
    description: "Base de lançamento de foguetes e satélites da Força Aérea Brasileira.",
  },
  {
    id: "clbi-barreira-do-inferno",
    name: "Centro de Lançamento da Barreira do Inferno",
    kind: "aerospace",
    state: "RN",
    latitude: -5.9169,
    longitude: -35.1594,
    description: "Primeiro centro de lançamento de foguetes do Brasil, Parnamirim.",
  },
  // --- Aeroportos internacionais/estratégicos ---
  {
    id: "aero-bsb",
    name: "Aeroporto Internacional de Brasília (BSB)",
    kind: "airport",
    state: "DF",
    latitude: -15.8697,
    longitude: -47.9172,
    description: "Principal hub da capital federal.",
  },
  {
    id: "aero-gru",
    name: "Aeroporto Internacional de Guarulhos (GRU)",
    kind: "airport",
    state: "SP",
    latitude: -23.4356,
    longitude: -46.4731,
    description: "Maior aeroporto do Brasil em movimento de passageiros e cargas.",
  },
  {
    id: "aero-cgh",
    name: "Aeroporto de Congonhas (CGH)",
    kind: "airport",
    state: "SP",
    latitude: -23.6261,
    longitude: -46.6564,
    description: "Principal ponte aérea doméstica, zona urbana de São Paulo.",
  },
  {
    id: "aero-gig",
    name: "Aeroporto Internacional do Galeão (GIG)",
    kind: "airport",
    state: "RJ",
    latitude: -22.8099,
    longitude: -43.2505,
    description: "Principal aeroporto internacional do Rio de Janeiro.",
  },
  {
    id: "aero-ssa",
    name: "Aeroporto Internacional de Salvador (SSA)",
    kind: "airport",
    state: "BA",
    latitude: -12.9086,
    longitude: -38.3225,
    description: "Principal hub aéreo do Nordeste soteropolitano.",
  },
  {
    id: "aero-rec",
    name: "Aeroporto Internacional do Recife (REC)",
    kind: "airport",
    state: "PE",
    latitude: -8.1264,
    longitude: -34.9236,
    description: "Principal hub aéreo do Nordeste.",
  },
  {
    id: "aero-for",
    name: "Aeroporto Internacional de Fortaleza (FOR)",
    kind: "airport",
    state: "CE",
    latitude: -3.7761,
    longitude: -38.5326,
    description: "Principal porta de entrada aérea do Ceará.",
  },
  {
    id: "aero-bel",
    name: "Aeroporto Internacional de Belém (BEL)",
    kind: "airport",
    state: "PA",
    latitude: -1.3792,
    longitude: -48.4763,
    description: "Principal porta de entrada aérea da Amazônia oriental.",
  },
  {
    id: "aero-mao",
    name: "Aeroporto Internacional de Manaus (MAO)",
    kind: "airport",
    state: "AM",
    latitude: -3.0386,
    longitude: -60.0497,
    description: "Principal hub aéreo da Amazônia ocidental, zona franca.",
  },
  {
    id: "aero-poa",
    name: "Aeroporto Internacional de Porto Alegre (POA)",
    kind: "airport",
    state: "RS",
    latitude: -29.9939,
    longitude: -51.1714,
    description: "Principal hub aéreo do extremo sul do Brasil.",
  },
  {
    id: "aero-cwb",
    name: "Aeroporto Internacional de Curitiba (CWB)",
    kind: "airport",
    state: "PR",
    latitude: -25.5285,
    longitude: -49.1758,
    description: "Principal hub aéreo do sul do Brasil, São José dos Pinhais.",
  },
  {
    id: "aero-igu",
    name: "Aeroporto Internacional de Foz do Iguaçu (IGU)",
    kind: "airport",
    state: "PR",
    latitude: -25.6002,
    longitude: -54.4854,
    description: "Tríplice fronteira Brasil-Argentina-Paraguai.",
  },
  {
    id: "aero-bvb",
    name: "Aeroporto Internacional de Boa Vista (BVB)",
    kind: "airport",
    state: "RR",
    latitude: 2.8413,
    longitude: -60.69,
    description: "Porta de entrada aérea da fronteira norte, próxima à Venezuela.",
  },
  // --- Delegacias/Superintendências da Polícia Federal (sedes) ---
  {
    id: "pf-sr-sp",
    name: "Superintendência da PF em São Paulo",
    kind: "federal_police",
    state: "SP",
    latitude: -23.5558,
    longitude: -46.635,
    description: "Sede da Polícia Federal no estado de São Paulo.",
  },
  {
    id: "pf-sr-rj",
    name: "Superintendência da PF no Rio de Janeiro",
    kind: "federal_police",
    state: "RJ",
    latitude: -22.8934,
    longitude: -43.2412,
    description: "Sede da Polícia Federal no estado do Rio de Janeiro, Ilha do Governador.",
  },
  {
    id: "pf-sr-df",
    name: "Superintendência da PF no Distrito Federal",
    kind: "federal_police",
    state: "DF",
    latitude: -15.8064,
    longitude: -47.8952,
    description: "Sede da Polícia Federal na capital federal.",
  },
  {
    id: "pf-sr-ba",
    name: "Superintendência da PF na Bahia",
    kind: "federal_police",
    state: "BA",
    latitude: -12.9822,
    longitude: -38.4661,
    description: "Sede da Polícia Federal no estado da Bahia, Salvador.",
  },
  {
    id: "pf-sr-pe",
    name: "Superintendência da PF em Pernambuco",
    kind: "federal_police",
    state: "PE",
    latitude: -8.0578,
    longitude: -34.8829,
    description: "Sede da Polícia Federal no estado de Pernambuco, Recife.",
  },
  {
    id: "pf-sr-am",
    name: "Superintendência da PF no Amazonas",
    kind: "federal_police",
    state: "AM",
    latitude: -3.1019,
    longitude: -60.0217,
    description: "Sede da Polícia Federal no estado do Amazonas, Manaus.",
  },
  {
    id: "pf-sr-rs",
    name: "Superintendência da PF no Rio Grande do Sul",
    kind: "federal_police",
    state: "RS",
    latitude: -30.0331,
    longitude: -51.23,
    description: "Sede da Polícia Federal no estado do Rio Grande do Sul, Porto Alegre.",
  },
  {
    id: "pf-sr-pr",
    name: "Superintendência da PF no Paraná",
    kind: "federal_police",
    state: "PR",
    latitude: -25.4483,
    longitude: -49.28,
    description: "Sede da Polícia Federal no estado do Paraná, Curitiba.",
  },
  {
    id: "pf-sr-mg",
    name: "Superintendência da PF em Minas Gerais",
    kind: "federal_police",
    state: "MG",
    latitude: -19.9167,
    longitude: -43.9333,
    description: "Sede da Polícia Federal no estado de Minas Gerais, Belo Horizonte.",
  },
  {
    id: "pf-sr-ce",
    name: "Superintendência da PF no Ceará",
    kind: "federal_police",
    state: "CE",
    latitude: -3.7827,
    longitude: -38.5388,
    description: "Sede da Polícia Federal no estado do Ceará, Fortaleza.",
  },
  // --- Postos de fronteira (delegacias e controle migratório) ---
  {
    id: "pf-foz-iguacu",
    name: "Delegacia da PF — Foz do Iguaçu (fronteira tríplice)",
    kind: "border_post",
    state: "PR",
    latitude: -25.5478,
    longitude: -54.5882,
    description: "Controle migratório na fronteira Brasil-Argentina-Paraguai, Ponte da Amizade.",
  },
  {
    id: "pf-uruguaiana",
    name: "Delegacia da PF — Uruguaiana (fronteira com Argentina)",
    kind: "border_post",
    state: "RS",
    latitude: -29.7546,
    longitude: -57.0864,
    description: "Controle migratório e aduaneiro, Ponte Internacional da Concórdia.",
  },
  {
    id: "pf-corumba",
    name: "Delegacia da PF — Corumbá (fronteira com Bolívia)",
    kind: "border_post",
    state: "MS",
    latitude: -19.0078,
    longitude: -57.6547,
    description: "Controle migratório na fronteira com a Bolívia.",
  },
  {
    id: "pf-tabatinga",
    name: "Delegacia da PF — Tabatinga (fronteira com Colômbia/Peru)",
    kind: "border_post",
    state: "AM",
    latitude: -4.2517,
    longitude: -69.9386,
    description: "Tríplice fronteira amazônica, Brasil-Colômbia-Peru.",
  },
  {
    id: "pf-pacaraima",
    name: "Delegacia da PF — Pacaraima (fronteira com Venezuela)",
    kind: "border_post",
    state: "RR",
    latitude: 4.4394,
    longitude: -61.1514,
    description: "Principal ponto de entrada terrestre da fronteira com a Venezuela.",
  },
  {
    id: "pf-santana-do-livramento",
    name: "Delegacia da PF — Santana do Livramento (fronteira com Uruguai)",
    kind: "border_post",
    state: "RS",
    latitude: -30.8908,
    longitude: -55.5328,
    description: "Cidades-gêmeas Livramento/Rivera, fronteira seca com o Uruguai.",
  },
  // --- Subestações elétricas e refinarias (energia crítica) ---
  {
    id: "se-ibiuna",
    name: "Subestação Ibiúna",
    kind: "power_grid",
    state: "SP",
    latitude: -23.6531,
    longitude: -47.1928,
    description: "Principal ponto de conversão da energia de Itaipu (corrente contínua) pro sistema interligado nacional.",
  },
  {
    id: "se-foz-margem-direita",
    name: "Subestação Foz do Iguaçu (Margem Direita) — Itaipu",
    kind: "power_grid",
    state: "PR",
    latitude: -25.4102,
    longitude: -54.6122,
    description: "Ponto de escoamento da energia gerada em Itaipu pro sistema brasileiro.",
  },
  {
    id: "se-xingu",
    name: "Subestação Xingu — Belo Monte",
    kind: "power_grid",
    state: "PA",
    latitude: -3.0489,
    longitude: -51.8867,
    description: "Hub de conversão e transmissão da energia de Belo Monte, elos de corrente contínua até Minas Gerais/SP.",
  },
  {
    id: "se-serra-da-mesa",
    name: "Subestação Serra da Mesa",
    kind: "power_grid",
    state: "GO",
    latitude: -13.85,
    longitude: -48.3,
    description: "Nó estratégico de transmissão entre Norte/Nordeste e Sudeste do SIN.",
  },
  {
    id: "replan",
    name: "REPLAN — Refinaria de Paulínia",
    kind: "power_grid",
    state: "SP",
    latitude: -22.7686,
    longitude: -47.1358,
    description: "Maior refinaria de petróleo do Brasil (Petrobras).",
  },
  {
    id: "reduc",
    name: "REDUC — Refinaria Duque de Caxias",
    kind: "power_grid",
    state: "RJ",
    latitude: -22.7189,
    longitude: -43.3125,
    description: "Grande refinaria da Petrobras na Baixada Fluminense.",
  },
  {
    id: "rlam",
    name: "RLAM — Refinaria Landulpho Alves (Mataripe)",
    kind: "power_grid",
    state: "BA",
    latitude: -12.6469,
    longitude: -38.6461,
    description: "Principal refinaria do Nordeste, Baía de Todos os Santos.",
  },
  // --- Água e esgoto (saneamento crítico) ---
  {
    id: "eta-guaraú",
    name: "ETA Guaraú — Sistema Cantareira",
    kind: "water_sanitation",
    state: "SP",
    latitude: -23.4547,
    longitude: -46.7439,
    description: "Maior estação de tratamento de água da América Latina, abastece boa parte da Grande São Paulo (Sabesp).",
  },
  {
    id: "eta-guandu",
    name: "ETA Guandu",
    kind: "water_sanitation",
    state: "RJ",
    latitude: -22.8069,
    longitude: -43.5967,
    description: "Maior estação de tratamento de água do mundo em volume, abastece a Região Metropolitana do Rio.",
  },
  {
    id: "ete-barueri",
    name: "ETE Barueri",
    kind: "water_sanitation",
    state: "SP",
    latitude: -23.4886,
    longitude: -46.8994,
    description: "Maior estação de tratamento de esgoto da América Latina (Sabesp).",
  },
  {
    id: "eta-bolandeira",
    name: "ETA Bolandeira",
    kind: "water_sanitation",
    state: "BA",
    latitude: -12.9264,
    longitude: -38.4406,
    description: "Principal estação de tratamento de água de Salvador (Embasa).",
  },
  // --- Comandos e grandes unidades do Exército ---
  {
    id: "cmp-brasilia",
    name: "Comando Militar do Planalto — QG do Exército",
    kind: "army",
    state: "DF",
    latitude: -15.7934,
    longitude: -47.8822,
    description: "Sede do Comando do Exército Brasileiro, Setor Militar Urbano.",
  },
  {
    id: "cml-rio",
    name: "Comando Militar do Leste",
    kind: "army",
    state: "RJ",
    latitude: -22.9035,
    longitude: -43.1822,
    description: "Um dos maiores comandos do Exército, região Sudeste/RJ-ES.",
  },
  {
    id: "cmse-sao-paulo",
    name: "Comando Militar do Sudeste",
    kind: "army",
    state: "SP",
    latitude: -23.5629,
    longitude: -46.6544,
    description: "Comando do Exército responsável por São Paulo e Mato Grosso do Sul.",
  },
  {
    id: "cma-manaus",
    name: "Comando Militar da Amazônia",
    kind: "army",
    state: "AM",
    latitude: -3.1019,
    longitude: -60.0217,
    description: "Comando responsável pela vigilância e defesa da fronteira amazônica.",
  },
  {
    id: "cms-porto-alegre",
    name: "Comando Militar do Sul",
    kind: "army",
    state: "RS",
    latitude: -30.0331,
    longitude: -51.23,
    description: "Comando do Exército responsável pela fronteira sul (Argentina/Uruguai).",
  },
  {
    id: "cmne-recife",
    name: "Comando Militar do Nordeste",
    kind: "army",
    state: "PE",
    latitude: -8.0578,
    longitude: -34.8829,
    description: "Comando do Exército responsável pela região Nordeste.",
  },
  {
    id: "cmo-campo-grande",
    name: "Comando Militar do Oeste",
    kind: "army",
    state: "MS",
    latitude: -20.4697,
    longitude: -54.6201,
    description: "Comando do Exército responsável pela fronteira oeste (Bolívia/Paraguai).",
  },
  // --- Portos estratégicos ---
  {
    id: "porto-santos",
    name: "Porto de Santos",
    kind: "port",
    state: "SP",
    latitude: -23.9608,
    longitude: -46.3039,
    description: "Maior porto da América Latina em movimentação de cargas.",
  },
  {
    id: "porto-paranagua",
    name: "Porto de Paranaguá",
    kind: "port",
    state: "PR",
    latitude: -25.5009,
    longitude: -48.5222,
    description: "Segundo maior porto do país, principal escoadouro de grãos do Sul.",
  },
  {
    id: "porto-itaqui",
    name: "Porto de Itaqui",
    kind: "port",
    state: "MA",
    latitude: -2.5697,
    longitude: -44.3689,
    description: "Principal porto de águas profundas do Norte/Nordeste.",
  },
  {
    id: "porto-suape",
    name: "Porto de Suape",
    kind: "port",
    state: "PE",
    latitude: -8.3961,
    longitude: -34.9689,
    description: "Complexo industrial-portuário estratégico de Pernambuco.",
  },
  {
    id: "porto-rio",
    name: "Porto do Rio de Janeiro",
    kind: "port",
    state: "RJ",
    latitude: -22.895,
    longitude: -43.1917,
    description: "Principal porto da Baía de Guanabara.",
  },
  // --- Telecomunicações / infraestrutura de internet ---
  {
    id: "ptt-sp",
    name: "PTT.br São Paulo (NIC.br)",
    kind: "telecom",
    state: "SP",
    latitude: -23.5931,
    longitude: -46.6853,
    description: "Um dos maiores pontos de troca de tráfego de internet do mundo — praticamente todo o tráfego doméstico brasileiro passa por aqui.",
  },
  {
    id: "ptt-rj",
    name: "PTT.br Rio de Janeiro",
    kind: "telecom",
    state: "RJ",
    latitude: -22.9068,
    longitude: -43.1729,
    description: "Ponto de troca de tráfego de internet do Rio de Janeiro (IX.br).",
  },
  {
    id: "ptt-df",
    name: "PTT.br Brasília",
    kind: "telecom",
    state: "DF",
    latitude: -15.7801,
    longitude: -47.9292,
    description: "Ponto de troca de tráfego de internet da capital federal (IX.br).",
  },
];

export const STRATEGIC_KIND_META: Record<StrategicSiteKind, { label: string; icon: string; color: string }> = {
  nuclear: { label: "Nuclear", icon: "radio-outline", color: "#C05621" },
  hydro: { label: "Hidrelétrica", icon: "water-outline", color: "#1B4B8F" },
  aerospace: { label: "Aeroespacial", icon: "rocket-outline", color: "#5B21B6" },
  naval: { label: "Naval/Defesa", icon: "boat-outline", color: "#12813D" },
  airport: { label: "Aeroporto", icon: "airplane-outline", color: "#0369A1" },
  federal_police: { label: "Polícia Federal", icon: "shield-outline", color: "#1E293B" },
  border_post: { label: "Posto de fronteira", icon: "flag-outline", color: "#B45309" },
  power_grid: { label: "Energia (rede/refinaria)", icon: "flash-outline", color: "#B7791F" },
  water_sanitation: { label: "Água/esgoto", icon: "water-outline", color: "#0E7490" },
  army: { label: "Exército", icon: "shield-half-outline", color: "#365314" },
  port: { label: "Porto", icon: "boat-outline", color: "#155E75" },
  telecom: { label: "Telecom/Internet", icon: "wifi-outline", color: "#6D28D9" },
};

// Rodovias federais principais, como polilinhas aproximadas (poucos pontos
// de referência — não é georreferenciamento preciso do traçado completo,
// mas o suficiente pra situar corredores logísticos/estratégicos no mapa).
export interface StrategicRoute {
  id: string;
  name: string;
  description: string;
  points: Array<{ latitude: number; longitude: number }>;
}

export const STRATEGIC_ROUTES: StrategicRoute[] = [
  {
    id: "br-101",
    name: "BR-101 (Rodovia Translitorânea)",
    description: "Principal eixo rodoviário do litoral, Natal (RN) a Osório (RS).",
    points: [
      { latitude: -5.79, longitude: -35.21 },
      { latitude: -8.05, longitude: -34.9 },
      { latitude: -12.97, longitude: -38.5 },
      { latitude: -19.92, longitude: -40.34 },
      { latitude: -22.9, longitude: -43.2 },
      { latitude: -26.3, longitude: -48.85 },
      { latitude: -29.94, longitude: -50.27 },
    ],
  },
  {
    id: "br-116",
    name: "BR-116 (Rodovia Régis Bittencourt/Fernão Dias)",
    description: "Principal corredor sul-nordeste, Fortaleza (CE) a Jaguarão (RS).",
    points: [
      { latitude: -3.78, longitude: -38.53 },
      { latitude: -8.05, longitude: -37.05 },
      { latitude: -12.97, longitude: -38.5 },
      { latitude: -19.92, longitude: -43.94 },
      { latitude: -23.55, longitude: -46.63 },
      { latitude: -26.3, longitude: -48.85 },
      { latitude: -30.03, longitude: -51.23 },
      { latitude: -32.57, longitude: -53.38 },
    ],
  },
  {
    id: "br-040",
    name: "BR-040",
    description: "Corredor Brasília (DF) – Rio de Janeiro (RJ), via Belo Horizonte.",
    points: [
      { latitude: -15.87, longitude: -47.92 },
      { latitude: -18.0, longitude: -46.0 },
      { latitude: -19.92, longitude: -43.94 },
      { latitude: -22.0, longitude: -43.4 },
      { latitude: -22.9, longitude: -43.2 },
    ],
  },
  {
    id: "br-364",
    name: "BR-364",
    description: "Corredor Cuiabá (MT) – Rio Branco (AC), integração centro-oeste/norte.",
    points: [
      { latitude: -15.6, longitude: -56.1 },
      { latitude: -12.6, longitude: -60.1 },
      { latitude: -9.97, longitude: -62.0 },
      { latitude: -8.76, longitude: -63.9 },
      { latitude: -9.97, longitude: -67.81 },
    ],
  },
  {
    id: "br-163",
    name: "BR-163",
    description: "Corredor logístico do agronegócio, Cuiabá (MT) a Santarém (PA).",
    points: [
      { latitude: -15.6, longitude: -56.1 },
      { latitude: -11.86, longitude: -55.5 },
      { latitude: -9.07, longitude: -55.1 },
      { latitude: -4.24, longitude: -55.99 },
      { latitude: -2.44, longitude: -54.71 },
    ],
  },
  {
    id: "br-230",
    name: "BR-230 (Transamazônica)",
    description: "Corredor leste-oeste da Amazônia, João Pessoa (PB) a Lábrea (AM).",
    points: [
      { latitude: -7.12, longitude: -34.86 },
      { latitude: -5.53, longitude: -47.48 },
      { latitude: -3.71, longitude: -49.68 },
      { latitude: -4.25, longitude: -55.99 },
      { latitude: -7.32, longitude: -64.8 },
      { latitude: -7.26, longitude: -64.8 },
    ],
  },
];
